import React from 'react'
import { onEnterNext, today } from '../utils/helpers.js'


export function StudentForm({onSubmit}){return <form onSubmit={onSubmit} onKeyDown={onEnterNext} className="form"><div className="form2"><label>Nombre*<input name="nombre" required/></label><label>Apellido*<input name="apellido" required/></label></div><div className="form2"><label>Edad<input name="edad" placeholder="Ej. 25"/></label><label>DNI<input name="dni" placeholder="Solo números"/></label></div><label>Fecha de nacimiento<input name="fecha_nac" type="date" /></label><div className="form2"><label>Enfoque<select name="enfoque" defaultValue="Hipertrofia"><option>Hipertrofia</option><option>Fuerza</option><option>Resistencia</option><option>Definición</option><option>Funcional</option><option>Rehabilitación</option></select></label><label>Nro de teléfono<input name="phone" placeholder="Ej. 221 555-0100"/></label></div><label>Mail<input name="mail" type="email" placeholder="ej@mail.com"/></label><label>Observaciones<textarea name="observaciones" rows="2" placeholder="Alergias, lesiones, objetivos..." style={{resize:'vertical',border:'1px solid var(--card-border)',background:'var(--input)',color:'var(--text)',borderRadius:10,padding:'10px'}}/></label><label>Fecha de ingreso (DD/MM/AAAA)<input name="joinedAt" defaultValue={today()} placeholder="DD/MM/AAAA" required/></label><button className="primary wide">Guardar alumno</button></form>}

export function PaymentForm({students,onSubmit,initialStudentId}){return <form onSubmit={onSubmit} onKeyDown={onEnterNext} className="form"><label>Alumno<select name="studentId" required defaultValue={initialStudentId||''}><option value="">Seleccionar...</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} — DNI {s.dni||'—'}</option>)}</select></label><div className="form2"><label>Monto<input name="amount" type="number" min="0" required/></label><label>Fecha<input name="date" type="date" defaultValue={today()}/></label></div><label>Detalle<input name="note" placeholder="Ej. Cuota septiembre"/></label><button className="primary wide">Registrar pago</button></form>}

export function RoutineForm({students,onSubmit}){return <form onSubmit={onSubmit} onKeyDown={onEnterNext} className="form"><label>Alumno<select name="studentId" required><option value="">Seleccionar...</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="form2"><label>Día<select name="day">{[1,2,3,4,5,6,7].map(n=><option key={n}>Día {n}</option>)}</select></label><label>Ejercicio<input name="exercise" required/></label></div><div className="form2"><label>Series<input name="series" placeholder="4"/></label><label>Repeticiones<input name="reps" placeholder="10-12"/></label></div><label>Observaciones<input name="notes"/></label><button className="primary wide">Agregar ejercicio</button></form>}

export function ClaseForm({onSubmit, profesores=[]}){return <form onSubmit={onSubmit} onKeyDown={onEnterNext} className="form"><label>Nombre de la clase<input name="nombre" placeholder="Funcional" required/></label><div className="form2"><label>Día<select name="dia" defaultValue="Lunes" required><option>Lunes</option><option>Martes</option><option>Miércoles</option><option>Jueves</option><option>Viernes</option><option>Sábado</option><option>Domingo</option></select></label><label>Profesor<select name="profesor" required><option value="">Seleccionar...</option>{profesores.map(p=><option key={p.id} value={p.nombreCompleto||`${p.nombre} ${p.apellido}`}>{p.nombreCompleto||`${p.nombre} ${p.apellido}`} — {p.especialidad}</option>)}{!profesores.length&&<option disabled>No hay profesores — cargalos en Profesores</option>}</select></label></div><div className="form2"><label>Inicio<input name="inicio" type="time" defaultValue="08:00"/></label><label>Fin<input name="fin" type="time" defaultValue="09:00"/></label></div><label>Capacidad<select name="cap" defaultValue="20"><option>2</option><option>4</option><option>6</option><option>8</option><option>10</option><option>12</option><option>14</option><option>16</option><option>18</option><option>20</option><option>22</option><option>24</option><option>26</option><option>28</option><option>30</option><option>Ilimitada</option></select></label><button className="primary wide">Crear clase</button></form>}

export function ProfesorForm({onSubmit}){return <form onSubmit={onSubmit} onKeyDown={onEnterNext} className="form"><div className="form2"><label>Nombre*<input name="nombre" required/></label><label>Apellido*<input name="apellido" required/></label></div><label>Teléfono<input name="telefono" placeholder="221 555-0100"/></label><label>Especialidad<select name="especialidad" defaultValue="General"><option>General</option><option>Musculación</option><option>Funcional</option><option>CrossFit</option><option>Yoga</option><option>Pilates</option><option>Spinning</option><option>Boxeo</option><option>Nutrición</option></select></label><button className="primary wide">Guardar profesor</button></form>}

export function UsuarioForm({onSubmit}){return <form onSubmit={onSubmit} onKeyDown={onEnterNext} className="form"><label>Usuario<input name="usuario" required/></label><label>Clave<input name="clave" type="password" required/></label><label>Rol<select name="rol" defaultValue="Empleado"><option>Empleado</option><option>Dueño</option><option>Administrador</option></select></label><button className="primary wide">Crear usuario</button></form>}
